### ISSUE TITLE
Problem with user.ts

### ISSUE THREAD

**Issue by ghost** [doqedev/roauth.js#1]
So this line of code

```
var requestOptions = {
        method: 'GET',
        headers: headers,
    };

    return new Promise((res, rej) => {
        fetch("https://apis.roblox.com/oauth/v1/userinfo", requestOptions)
 
```

There's a problem. 

requestOptions.headers should not be the same as another variable name, this just causes memory leaks, errors and more bugs.

Instead you should do something like this:

```
var requestOptions = {
        method: 'GET',
        header: headers,
    };

    return new Promise((res, rej) => {
        fetch("https://apis.roblox.com/oauth/v1/userinfo", requestOptions)
```

Just replace the code that needs the requestOptions headers value with just `header` seen above, or eliminate it overall.

Hope this helped

**Comment by saike** [comment]
@DavidTDC3377 according to javascript [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), ```fetch``` method doesn't accept ```header``` property inside request parameters, that's why your proposal does not make sense.

**Comment by ghost** [comment]
@saike this is where you are wrong. It does accept header property. The problem was that it was formatted incorrectly. Ik proper JS I am not dumb

**Comment by saike** [comment]
@DavidTDC3377 of course you are not dumb. But let's check the documentation. 
<img width="277" alt="Screenshot 2023-06-15 at 22 52 47" src="https://github.com/doqedev/roauth.js/assets/1619473/447650d3-3070-480e-9623-be0181dc0bab">

there is no ```header``` property, only ```headers```

**Comment by ghost** [comment]
Ok then @saike I apologize I have not noticed this 👍

Closing...

**Comment by ghost** [comment]
Wrong close type
